name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Apply version-specific compatibility fixes
        run: |
          # Apply fixes based on the PHP version being tested
          php -f app/Compatibility/apply-fixes.php ${{ matrix.php }}

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Create storage symlink
        run: php artisan storage:link
        
      # Add Node.js and Vite build steps
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Copy debug Vite config
        run: cp vite.config.debug.js vite.config.js

      - name: Build assets
        run: |
          npm run build
          echo "Checking build output:"
          ls -la public/build/
          echo "Checking .vite subdirectory:"
          ls -la public/build/.vite/
          # Workaround: Copy manifest from .vite subdir if it exists there
          # Ideally, Vite config should output manifest to public/build/ directly
          if [ -f "public/build/.vite/manifest.json" ] && [ ! -f "public/build/manifest.json" ]; then
            echo "Copying manifest.json from .vite directory..."
            cp public/build/.vite/manifest.json public/build/manifest.json
          fi
          # Verify manifest exists in the expected location
          if [ -f "public/build/manifest.json" ]; then
            echo "manifest.json found in public/build:"
            cat public/build/manifest.json
          else
            echo "ERROR: manifest.json not found in public/build/ or public/build/.vite/"
            exit 1
          fi

      - name: Backup Database
        run: php artisan app:database-backup -vvv

      - name: Check Application Status
        run: php artisan app:check-status -vvv

      - name: Run Migrations
        run: php artisan migrate:safe --force -vvv

      - name: Seed Database
        run: php artisan db:seed -vvv

      - name: Execute tests
        run: php artisan test -vvv
