name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Apply version-specific compatibility fixes
        run: |
          if [[ "${{ matrix.php }}" == "8.3" ]]; then
            # Apply PHP 8.3 specific fixes if needed
            php -f app/Compatibility/apply-fixes.php
          fi

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      # Add Node.js and Vite build steps
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Copy debug Vite config
        run: cp vite.config.debug.js vite.config.js

      - name: Build assets
        run: |
          npm run build
          echo "Checking build output:"
          ls -la public/build/
          if [ -f "public/build/manifest.json" ]; then
            echo "manifest.json exists!"
            cat public/build/manifest.json
          else
            echo "ERROR: manifest.json not found!"
            exit 1
          fi

      - name: Execute tests
        run: php artisan test